---
name: fruit-jokes

services:
  app:
    image: ghcr.io/luislavena/hydrofoil-crystal:1.14
    command: overmind start -f Procfile.dev
    working_dir: /workspace/${COMPOSE_PROJECT_NAME}

    # Set these env variables using `export FIXUID=$(id -u) FIXGID=$(id -g)`
    user: ${FIXUID:-1000}:${FIXGID:-1000}

    volumes:
      - .:/workspace/${COMPOSE_PROJECT_NAME}
